### ISSUE TITLE
a fatal error in _crown_dalponte_numba.py 

### ISSUE THREAD

**Issue by yangshikai1997** [manaakiwhenua/pycrown#7]
Crowns on line 67 70 and 109 should be CrownsTemp

**Comment by zjans** [comment]
Thanks for letting me know. I haven't used the algorithm in a long time (I prefer the circular region growing).
I changed line 109 to ensure the region growing criteria considers crown pixels in the current iteration.
I left lines 67 and 70 as they were, because the algorithm should only walk around crown pixels from the previous iteration.

Looking at the minor effect in crown delineation, I wouldn't call this fatal.

Before:
![image](https://user-images.githubusercontent.com/39352402/87748717-cb2bc580-c84a-11ea-9b04-d9feae9dc0f3.png)

After:
![image](https://user-images.githubusercontent.com/39352402/87748772-f1516580-c84a-11ea-8510-997bcb19b447.png)
